### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PassAssociates** [AvanthikaMeenakshi/uthiramapp#4] opened 2019-05-21 11:32 UTC
Failed to compile
./src/index.js
Cannot find file: 'index.js' does not match the corresponding name on disk: '.\src\components\App\app'.
This error occurred during the build time and cannot be dismissed.

**Comment by ParkerSm1th** [comment] 2019-05-22 16:05
Same issue

**Comment by AvanthikaMeenakshi** [comment] 2019-05-22 16:13
Looking into it. Give me 30 minutes!

**Comment by ParkerSm1th** [comment] 2019-05-22 16:15
Thanks :)

**Comment by ParkerSm1th** [comment] 2019-05-23 05:15
> Looking into it. Give me 30 minutes!

Any updates?

**Comment by AvanthikaMeenakshi** [comment] 2019-05-23 09:25
Can you add more steps for me to reproduce? i'm unable to reproduce this on my end.

**Comment by ParkerSm1th** [comment] 2019-05-25 14:24
I've just attempted to run and it had this bug.

**Comment by AvanthikaMeenakshi** [comment] 2019-05-25 19:14
Hi, thanks for reporting this, I've fixed this issue and have updated the instructions.

**Comment by AvanthikaMeenakshi** [comment] 2019-06-07 13:58
Closing this issue as fixed.

**Closed by AvanthikaMeenakshi** 2019-06-07 13:58 UTC
